name: qr_code_vision
description: A pure Dart package for QR detection, decoding and tracking.
version: 0.1.1
homepage: https://github.com/alessandrodiano/qr_code_vision

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  image: ^4.0.0
  collection: ^1.15.0
  dart_reed_solomon_nullsafety: ^0.2.0
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.20.1
  barcode_image: 2.0.3
  flutter_lints: ^2.0.0
